check:
  - thoth-build
build:
  build-strategy: Dockerfile
  dockerfile-path: Dockerfile
  custom-tag: "latest"
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "s2i-lab-elyra"
  registry-secret: "thoth-station-thoth-pusher-secret"
