check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-minimal-py38-notebook:v0.1.0"
  build-stratergy: "Source"
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "s2i-lab-elyra"
  registry-secret: "thoth-station-thoth-pusher-secret"
